// USBProtection.cpp : Defines the entry point for the application.
//

#include "USBProtection.h"

using namespace std;

//Windows stuff
LRESULT CALLBACK WndProc(HWND hwnd, UINT msg, WPARAM wParam, LPARAM lParam) { //I think this triggers when a windows thing occurs
    if (msg == WM_DEVICECHANGE) {
        PDEV_BROADCAST_HDR lpHdr = (PDEV_BROADCAST_HDR)lParam;

        switch (wParam) {
        case DBT_DEVICEARRIVAL: //USB was plugged in
            std::cout << "[+] A device was plugged in! ";
            if (lpHdr && lpHdr->dbch_devicetype == DBT_DEVTYP_DEVICEINTERFACE) { //DBT describes plug-and-play stuff
                std::cout << "(USB Interface Detected)\n";

                PDEV_BROADCAST_DEVICEINTERFACE dev = //This is a pointer
                    reinterpret_cast<PDEV_BROADCAST_DEVICEINTERFACE>(lParam); //We treat the integer lParam as a pointer to DEV...

                cout << "DBCC NAME : " << dev->dbcc_name << endl;
            }
            else {
                std::cout << "\n";
            }
            break;

        case DBT_DEVICEREMOVECOMPLETE: //USB removed
            std::cout << "[-] A device was removed! ";
            if (lpHdr && lpHdr->dbch_devicetype == DBT_DEVTYP_DEVICEINTERFACE) {
                std::cout << "(USB Interface Disconnected)\n";
            }
            else {
                std::cout << "\n";
            }
            break;
        }
    }
    return DefWindowProc(hwnd, msg, wParam, lParam);
}

int main() {
    std::cout << "Listening for USB plugin events... Press Ctrl+C to exit.\n\n";

    //The below code was generated by AI and detects USBs being plugged in
    // 1. Register a dummy window class to receive system messages
    WNDCLASS wc = {};
    wc.lpfnWndProc = WndProc;
    wc.hInstance = GetModuleHandle(NULL);
    wc.lpszClassName = "USBDetectorClass";
    RegisterClass(&wc);

    // 2. Create a hidden background window
    HWND hwnd = CreateWindowEx(
        0, "USBDetectorClass", "USB Detector",
        0, 0, 0, 0, 0,
        HWND_MESSAGE, // Makes it a message-only background window
        NULL, NULL, NULL
    );

    if (!hwnd) {
        std::cerr << "Failed to create background message window.\n";
        return 1;
    }

    // 3. Register to receive specific notifications for USB Hubs/Devices
    DEV_BROADCAST_DEVICEINTERFACE notificationFilter = {};
    notificationFilter.dbcc_size = sizeof(DEV_BROADCAST_DEVICEINTERFACE);
    notificationFilter.dbcc_devicetype = DBT_DEVTYP_DEVICEINTERFACE;
    notificationFilter.dbcc_classguid = GUID_DEVINTERFACE_USB_DEVICE; // Fires for ALL USB devices

    HDEVNOTIFY hDevNotify = RegisterDeviceNotification(
        hwnd,
        &notificationFilter,
        DEVICE_NOTIFY_WINDOW_HANDLE
    );

    if (!hDevNotify) {
        std::cerr << "Failed to register device notifications. Error: " << GetLastError() << "\n";
        return 1;
    }

    // 4. Standard Windows Message Loop to keep the thread alive and processing
    MSG msg;
    while (GetMessage(&msg, NULL, 0, 0)) {
        TranslateMessage(&msg);
        DispatchMessage(&msg); //This calls the WndProc
    }

    // Cleanup when exiting
    UnregisterDeviceNotification(hDevNotify);
    return 0;
}