// USBProtection.cpp : Defines the entry point for the application.
//

#include "USBProtection.h"

using namespace std;

void DBCCParser(uint64_t* bufferInt, string* bufferStr, string dbcc) {
    string VID = dbcc.substr(12, 4);
    string PID = dbcc.substr(21, 4);
    string serial = dbcc.substr(26, 16);

    bufferStr[0] = VID;
    bufferStr[1] = PID;
    bufferStr[2] = serial;

    cout << "VID : " << VID << "\nPID : " << PID << "\nSerial : " << serial << endl;

    bufferInt[0] = stoull(VID, 0, 16);
    bufferInt[1] = stoull(PID, 0, 16);
    bufferInt[2] = stoull(serial, 0, 16);
}

void HandleUSB(DEV_BROADCAST_DEVICEINTERFACE* dev) {
    cout << "DBCC NAME : " << dev->dbcc_name << endl;
    uint64_t bufferInt[3] = { 0 };
    string bufferStr[3];
    DBCCParser(bufferInt, bufferStr, dev->dbcc_name);

    //Known systems storage
    //TODO - encrypt this
    ofstream fCreate("KnownCombinations.txt", ios_base::app);
    fCreate.close();
    
    ifstream fIn;
    fIn.open("KnownCombinations.txt");
    string fileBuffer;
    string name = "";

    while (getline(fIn, fileBuffer)) {
        if (
                (fileBuffer.substr(0, 04) == bufferStr[0])
            &&  (fileBuffer.substr(4, 04) == bufferStr[1])
            &&  (fileBuffer.substr(8, 16) == bufferStr[2])
            ){
            //We know this device already
            name = fileBuffer.substr(24, string::npos);

            cout << "Name : " << name << endl;
            break;
        }
    }

    fIn.close();

    if (name == "") {
        ofstream fOut("KnownCombinations.txt");

        cout << "New USB. Name : ";
        cin >> name;
        cout << endl;

        string out = bufferStr[0] + bufferStr[1] + bufferStr[2] + name + "\n";
        cout << "Out : " << out;
        fOut << out;

        fOut.close();
    }

}

//Windows stuff
LRESULT CALLBACK WndProc(HWND hwnd, UINT msg, WPARAM wParam, LPARAM lParam) { //I think this triggers when a windows thing occurs
    if (msg == WM_DEVICECHANGE) {
        PDEV_BROADCAST_HDR lpHdr = (PDEV_BROADCAST_HDR)lParam;

        switch (wParam) {
        case DBT_DEVICEARRIVAL: //USB was plugged in
            std::cout << "[+] A device was plugged in! ";
            if (lpHdr && lpHdr->dbch_devicetype == DBT_DEVTYP_DEVICEINTERFACE) { //DBT describes plug-and-play stuff
                std::cout << "(USB Interface Detected)\n";

                auto dev = ((DEV_BROADCAST_DEVICEINTERFACE*)lpHdr);

                HandleUSB(dev);
            }
            else {
                std::cout << "\n";
            }
            break;

        case DBT_DEVICEREMOVECOMPLETE: //USB removed
            std::cout << "[-] A device was removed! ";
            if (lpHdr && lpHdr->dbch_devicetype == DBT_DEVTYP_DEVICEINTERFACE) {
                std::cout << "(USB Interface Disconnected)\n";
            }
            else {
                std::cout << "\n";
            }
            break;
        }
    }
    return DefWindowProc(hwnd, msg, wParam, lParam);
}

int main() {
    std::cout << "Listening for USB plugin events... Press Ctrl+C to exit.\n\n";

    //The below code was generated by AI and detects USBs being plugged in
    // 1. Register a dummy window class to receive system messages
    WNDCLASS wc = {};
    wc.lpfnWndProc = WndProc;
    wc.hInstance = GetModuleHandle(NULL);
    wc.lpszClassName = "USBDetectorClass";
    RegisterClass(&wc);

    // 2. Create a hidden background window
    HWND hwnd = CreateWindowEx(
        0, "USBDetectorClass", "USB Detector",
        0, 0, 0, 0, 0,
        HWND_MESSAGE, // Makes it a message-only background window
        NULL, NULL, NULL
    );

    if (!hwnd) {
        std::cerr << "Failed to create background message window.\n";
        return 1;
    }

    // 3. Register to receive specific notifications for USB Hubs/Devices
    DEV_BROADCAST_DEVICEINTERFACE notificationFilter = {};
    notificationFilter.dbcc_size = sizeof(DEV_BROADCAST_DEVICEINTERFACE);
    notificationFilter.dbcc_devicetype = DBT_DEVTYP_DEVICEINTERFACE;
    notificationFilter.dbcc_classguid = GUID_DEVINTERFACE_USB_DEVICE; // Fires for ALL USB devices

    HDEVNOTIFY hDevNotify = RegisterDeviceNotification(
        hwnd,
        &notificationFilter,
        DEVICE_NOTIFY_WINDOW_HANDLE
    );

    if (!hDevNotify) {
        std::cerr << "Failed to register device notifications. Error: " << GetLastError() << "\n";
        return 1;
    }

    // 4. Standard Windows Message Loop to keep the thread alive and processing
    MSG msg;
    while (GetMessage(&msg, NULL, 0, 0)) {
        TranslateMessage(&msg);
        DispatchMessage(&msg); //This calls the WndProc
    }

    // Cleanup when exiting
    UnregisterDeviceNotification(hDevNotify);
    return 0;
}